### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by timothymarois** [jamesmoss/flywheel#29]
This is not an issue. I'm considering using this for one of my projects, and would like to know if this project has been abandoned? I see a decent todo list, however most of the commits are very old. And if this project has gone stale because of better alternatives, just let me know. Thanks.

**Comment by jamesmoss** [comment]
It's not been abandoned but I don't have time to work on it regularly however I'm still accepting pull requests and making releases.

Most of the todos in the readme right now are around improving performance for large datasets and adding more extension points rather than filling in missing functionality. If you're not pushing flywheel to the extreme then it should be fine for your project; the API is stable and we have good test coverage.

As for alternatives, I don't know of many, if any, but I haven't looked for at least 12 months. One of the reasons I wrote this library in the first place was because what was out there already was pretty poor in terms of code quality and tests but something newer and shinier might be around by now.

**Comment by timothymarois** [comment]
Okay thanks. Im going to play around with some of this to see what I can do.

**Comment by jacmoe** [comment]
I am using Flywheel because it does exactly what I want it to do.

The project might not be actively developed, but it is maintained, which I
appreciate :)

2017-07-25 3:29 GMT+02:00 Timothy Marois <notifications@github.com>:
